version: "3"
services:

  php:
    build:
      context: .
      dockerfile: docker/Dockerfile-php
    ports:
      - "8000:80"
    links:
      - db
    volumes:
      - .:/var/www/html/
  db:
    build:
      context: .
      dockerfile: docker/Dockerfile-mysql
    volumes:
      - ./docker/mysqldb:/var/lib/mysql
      - ./mysql:/etc/mysql/conf.d
    ports:
      - "3306:3306"
  composer:
    image: "composer:1.4.1"
    volumes:
      - .:/app
    command: composer install
    tty: true
